### PR TITLE
Fix incorrect unary precedence

### LINKED ISSUE #296: Incorrect unary precedence
The rewritten parser incorrectly treats unary precedence, thus parsing the following:
`local c = -a + b`

incorrectly gives:
`UnaryOperator(BinaryOperator(a, b))`
instead of the expected
`BinaryOperator(UnaryOperator(a), b)`

### PR DESCRIPTION
**Pull request by chriscerie**
Fixes #296.

### CODE REVIEW

File: full-moon/src/ast/mod.rs [hunk 1]
```diff
@@ -2074,6 +2074,11 @@ macro_rules! make_bin_op {
                     }
                 }
 
+                /// The precedence of unary operators
+                pub fn precedence_of_unary() -> u8 {
+                    11
+                }
```
Comment (chriscerie) [inline full-moon/src/ast/mod.rs:2080]: This seems a bit weird. Is there a better approach?

File: full-moon/src/ast/parsers.rs [hunk 2]
```diff
@@ -1815,7 +1815,26 @@ fn parse_unary_expression(
...
+            );
+            return ParserResult::NotFound;
+        }
+        ParserResult::LexerMoved => return ParserResult::LexerMoved,
+    };
+
+    let expression = match parse_expression_with_precedence(
+        state,
+        primary_expression,
+        ast::BinOp::precedence_of_unary(),
```
Comment (JohnnyMorganz) [inline full-moon/src/ast/parsers.rs:1836]: nit: why not just add `precedence()` to UnOp instead?

**Review by JohnnyMorganz — APPROVED** [review]
LGTM (I did not look at the snapshots in detail as GitHub doesn't display it in a useful way, will try to look in better detail in code editor later)

Can you also add the test cases that I initially sent on Discord?
